# Generated by Django 2.2.4 on 2019-08-31 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Estreia', models.DateField()),
                ('Diretores', models.CharField(blank=True, max_length=100, null=True)),
                ('Estrelando', models.CharField(blank=True, max_length=100, null=True)),
                ('Resenha', models.TextField(max_length=250)),
                ('Genero', models.CharField(blank=True, choices=[('Ação', 'Ação'), ('Animação', 'Animação'), ('Comedia', 'Comedia'), ('Drama', 'Drama'), ('Ficção científica', 'Ficção científica'), ('Infantil', 'Infantil'), ('Suspense', 'Suspense'), ('Terror', 'Terror'), ('Outros', 'Outros')], max_length=20, null=True)),
                ('Classificação', models.CharField(blank=True, choices=[('Livre', 'Livre'), ('+12', '+12'), ('+10', '+10'), ('+14', '+14'), ('+16', '+16'), ('+18', '+18')], max_length=10, null=True)),
                ('Produção', models.CharField(blank=True, max_length=100, null=True)),
                ('Publicado', models.DateTimeField()),
                ('Edição', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
