# Generated by Django 2.2.4 on 2019-09-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenhando', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='Publicado',
            field=models.DateTimeField(verbose_name='Postado em'),
        ),
    ]
