# Generated by Django 2.2.4 on 2019-08-28 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controller', '0002_auto_20190828_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premiere', models.DateTimeField()),
                ('directors', models.CharField(max_length=100)),
                ('starring', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=20)),
                ('parental_rating', models.CharField(max_length=5)),
                ('production', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
