# Generated by Django 2.2.4 on 2019-08-29 17:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_auto_20190829_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='premiere',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 17, 1, 43, 257724, tzinfo=utc)),
        ),
    ]
