# Generated by Django 2.2.4 on 2019-08-29 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_auto_20190829_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='premiere',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
